version: '3'

services: 
  nflow-api:
    build: .
    ports: 
      - "3000:3000"
    volumes: 
      - .:/home/node/app
    command: "npm run dev"
  nflow-sql:
    image: postgres:12.2
    ports: 
      - 5432:5432
    environment: 
      - "POSTGRES_PASSWORD=${SQL_PASSWORD}"
      - "POSTGRES_USER=${SQL_USER}"
      - "POSTGRES_DB=${SQL_DB}"
    volumes:
      - ./data:/var/postgresql/data

 